twitchusersurl: "https://api.twitch.tv/helix/users"
twitchstreamscheduleurl: "https://api.twitch.tv/helix/schedule"
clientid: your_id
clientsecret: your_secret
telegramtoken: your_token
mongo: "mongodb://127.0.0.1:27117"
redirecturl: "http://localhost:8080"